[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
airdropper_solana = "3skgrkCMK7ntA99KBJGaTB5DWHpyrT3QgzCkVyGcHGtb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
